feat(Data Grid): align resize coulum PAL pattern
carbon-design-system/ibm-products pull request #2346
Opened 2022-10-11 09:52 UTC by Ratheeshrajan

Contributes to #1923

**Resize multiple columns at a time :**

- Hold Shift, and hover over the right side of any column header until a horizontal split cursor appears. Click on the resizer to select the columns. 
 ![image](https://user-images.githubusercontent.com/305492/195056359-a6fa98d2-efdd-429e-9d1a-9a8c875b19f5.png)

- Double-click the column resizer to resize all visible columns to fit the content.
![image](https://user-images.githubusercontent.com/305492/195056770-d97a2174-bac6-4fcc-ab16-ff56a1a64335.png)

- Display minimum of one letter in a column
![image](https://user-images.githubusercontent.com/305492/195056859-c9b3cbe9-0f82-4da3-bce1-4f4006245646.png)
- Wrap column header titles
![image](https://user-images.githubusercontent.com/305492/195056982-d3670eaa-8435-436a-a4b8-a657cbcbc050.png)

#### What did you change?
Datagrid/DatagridHeaderRow.js
Datagrid/DatagridRow.js
Datagrid/Datagrid.stories.js
styles/_datagrid.scss

#### How did you test and verify your work?
Storybook

Keyboard navigation will be covered in another PR later.

2022-10-13 06:13 UTC, Ratheeshrajan commented
V-11 PR added https://github.com/carbon-design-system/ibm-cloud-cognitive/pull/2352

2022-10-28 15:17 UTC, matthewgallo commented
Hey @Ratheeshrajan, I'm noticing an issue where if I resize multiple columns then try to resize a single column, I'm not able to resize the single column anymore.

2022-10-28 15:21 UTC, matthewgallo commented on packages/cloud-cognitive/src/components/Datagrid/Datagrid/DatagridHeaderRow.js
> +  const [dargStopped, setDargStopped] = useState(false);
Typo `darg` => `drag`

2022-10-28 19:47 UTC, matthewgallo requested changes
I'm noticing an issue where if I resize multiple columns then try to resize a single column, I'm not able to resize the single column anymore. I'm also noticing the same behavior after the double click interaction on a column, not able to resize that column anymore afterwards.

2023-04-06 20:01 UTC, AlexanderMelox commented
Weird bug when resizing the first column to the smallest width
https://user-images.githubusercontent.com/12755042/230482191-0d6110f3-bc0a-4a2e-a9cf-2b7ab40fbd2e.mov

2023-04-12 17:26 UTC, elycheea commented
@Ratheeshrajan Looks like there’s a conflict in the SCSS still!

2023-05-16 06:21 UTC, Ratheeshrajan commented
> @Ratheeshrajan Weird bug when resizing columns to the smallest width https://user-images.githubusercontent.com/12755042/230482191-0d6110f3-bc0a-4a2e-a9cf-2b7ab40fbd2e.mov

@AlexanderMelox It's an existing issue width React table `state.columnResizing` event. It's not stopping the resize event even if reached `width:0` and it's goes to `-` value in `columnResizing.columnWidth` and then resets the column width to the column `originalWidth` 150px, also it's ignoring the min-widths as well. This happens if we resize very fast. I have tried a workaround that I can provide this time, if the column width goes beyond the min-width and rests back to the original width then can rest the column width to a min-width 50. The issue with this approach is, this will only take effect after the Reat table `columnResizing` ends. So we can see a slight flickering when we are resizing very fast. This issue is reproducible in Carbon for IBM Storybook.  

Issue in https://carbon-for-ibm-products.netlify.app/:
https://github.com/carbon-design-system/ibm-cloud-cognitive/assets/305492/aee54cc1-1f76-4986-9993-2f05c4142a05

Workaround:

https://github.com/carbon-design-system/ibm-cloud-cognitive/assets/305492/b73bc794-2cda-4b37-a5dc-f0526578985f

2023-11-07 01:52 UTC, matthewgallo commented
Closing since there have been several updates to resizing since this PR was initially opened. But for documentation purposes, our current approach utilizes the `stateReducer` that `react-table` supports and that's how we've been able to hook into updating `datagridState.state`. By dispatching actions in this reducer and providing this reducer to the `useTable` hook, those `state` values are always synched with the resized value.

2023-11-07 01:52 UTC, closed without merging