feat: add second gallery
carbon-design-system/ibm-products pull request #3010
Opened 2023-05-16 16:49 UTC by lee-chase

Contributes to #2884 

Show gallery for codesandbox and stackblitz

#### What did you change?

- Additional story added
- Moved some paths from config builder script to gallery
- Changed config url for directory hosting example
- Corrected thumbnail for prefix-example
- Corrected prefix example usage of about modal
- Listed stackblitz in readme.

#### How did you test and verify your work?

Ran up storybook and viewed the example galleries for both codesandbox and stackblitz

2023-05-16 18:01 UTC, matthewgallo requested changes

2023-05-16 18:01 UTC, matthewgallo commented on examples/carbon-for-ibm-products/example-gallery/src/components/Gallery.jsx
> +              // url={item.url}
Remove comment

2023-05-16 18:06 UTC, matthewgallo approved these changes

2023-05-16 18:43 UTC, merged

2023-05-18 13:20 UTC, elycheea commented
@allcontributors add @lee-chase for examples