fix(datagrid) : expand listener added
carbon-design-system/ibm-products pull request #3114
Opened 2023-06-09 10:06 UTC by jagathgj

Contributes to #2603 

Event listener function added to expandable rows.

#### What did you change?
ExpandableRow.stories.js
Datagrid/index.js
useRowExpandListener.js

#### How did you test and verify your work?
storybook

2023-06-13 15:05 UTC, davidmenendez approved these changes
code wise this looks good to me. not sure if anyone who's more familiar with datagrid wants to chime in though.

2023-06-21 14:02 UTC, AlexanderMelox commented on packages/ibm-products/src/components/Datagrid/useRowExpandListener.js
> +        }
```suggestion
          row?.original?.onRowExpand?.(row);
```

I would make this less bloated

2023-06-21 14:07 UTC, AlexanderMelox commented
@jagathgj I think it should be fine to just add it to `useExpandedRow`, the onExpandRow can live in there. I don't see a need to make another hook just to listen to the row click 🤔 Any thoughts on this @matthewgallo

2023-06-21 19:08 UTC, matthewgallo requested changes
Agree with @AlexanderMelox, I don't think this necessarily is something that needs it's own hook. There are other extensions which add a listener without the need for a completely new hook.

2023-10-05 14:23 UTC, elycheea commented
@jagathgj Sorry for the delay on this one — seems like we keep missing it, but looks like we have a conflict with one of the recent PRs now but once we resolve, @matthewgallo can help re-review this.

2024-02-02 14:35 UTC, matthewgallo requested changes
To follow the pattern we've set with other event handlers like this, I think it makes most sense to have `onRowExpand` be passed directly to the `useDatagrid` hook and it returns the row that was expanded. As opposed to this approach which adds it directly on the row within the data.

2024-02-07 15:21 UTC, matthewgallo approved these changes

2024-02-07 15:31 UTC, merged