feat(InterstitialScreen): Novice to Pro component
carbon-design-system/ibm-products pull request #3236
Opened 2023-07-17 14:22 UTC by jlongshore

Contributes to:
Novice to Pro components

Added the following components and stories:
InterstitialScreen
InterstitialScreenView

How did you test and verify your work?
Storybook in addition to internal code and design reviews.

2023-09-14 15:49 UTC, elycheea commented
@jlongshore Worried we might have had a merge from `main` instead of `main_v1` here — hence the conflicts. 👀  Not sure if you want to save your changes in n2p and open a new PR / branch. (Don’t delete the branch if you wanna do that as @paul-balchin-ibm learned in the past 😹)

2023-09-14 18:06 UTC, jlongshore commented on packages/ibm-products/src/components/Carousel/Carousel.js
This was an issue we found with allowing the scroll event to bubble up beyond the carousel & its items when the carousel's height is causing scrollbar on a parent element. If the cursor was over the cursor the vertical scroll wouldn't work

2023-09-14 18:07 UTC, jlongshore commented on packages/ibm-products/src/components/Carousel/Carousel.js
I call this out because I know its not directly an interstitial screen item... just used internally. Happy to break it out if need be.

2023-10-03 21:31 UTC, elycheea requested changes
Mostly have some structural questions and suggestions and a handful of small catches.
Stories can probably be cleaned up to a few variants (can reduce some overhead). Definitely should add a little bit of docs in the mdx file so we can explain how InterstitialScreen the subcomponents should be used together.

The ComposedModal / full page one might be worth bringing up with the larger group since I’m sure whoever worked on create flows can share some insight if that was some of the reason why we did not use `ComposedModal`.

2023-10-03 21:31 UTC, elycheea commented on packages/ibm-products/src/components/InterstitialScreen/_interstitial-screen.scss
Some differing opinions on this one, but I _usually_ prefer that we type out the classnames since it makes it a bit quicker to locate when bugs arise. We have a few places we do this though so it’s not really a requested change just a thought/discussion.

2023-10-03 21:31 UTC, elycheea commented on packages/ibm-products/src/components/InterstitialScreen/InterstitialScreen.mdx
Probably worth doing some brief introduction on `InterstitialScreen` and its subcomponents here since I had to ask you about it directly, haha.

2023-12-12 22:46 UTC, jlongshore commented on packages/ibm-products/src/components/InterstitialScreen/InterstitialScreen.js
> +        <div className={containerClass}>
Modal variant now uses ComposedModal under the hood.

2023-12-12 23:05 UTC, jlongshore commented on packages/ibm-products/src/components/InterstitialScreen/InterstitialScreen.stories.js
I dig it, I did stay with 'Full screen' rather than 'Full page' as I believe the usage guidelines as well as the prop being called 'isFullScreen'... I like the simplification and agree - users can toggle / modify all this with the controls provided.

2023-12-20 20:17 UTC, elycheea reviewed
Changes are looking good. Small comments left in.

In general, we try to use `getByRole`[^1] over a test ID, but I’d rather not block the PR over something like this. I think if we can remove the one comment, we can go ahead and merge this. (Comments are small, but I always worry we’ll never remove them otherwise. There might be a preferred way to query, but what you have still works.)

[^1]: https://kentcdodds.com/blog/common-mistakes-with-react-testing-library#not-using-byrole-most-of-the-time

2023-12-20 20:17 UTC, elycheea commented on packages/ibm-products/src/components/InterstitialScreenViewModule/_interstitial-screen-view-module.scss
> +    // }
Probably safe to delete these?

```suggestion
```

2023-12-20 20:17 UTC, elycheea commented on packages/ibm-products/src/components/InterstitialScreen/InterstitialScreen.test.js
Nice seeing the accessibility checks on each variant. 🔥

2023-12-20 20:38 UTC, elycheea approved these changes
Closes #2892

2023-12-20 20:47 UTC, merged