(fix): fix for issue 3328
carbon-design-system/ibm-products pull request #3384
Opened 2023-08-21 07:19 UTC by rakesh-musturi

Contributes to #3328 

Previously selected filters re-appear after closing the fliter panel using the 'X' close button in the top right.
Only happens after clearing filter selections using the 'clear filters' button in the filter tag summary.

#### What did you change?
Commented the function revertToPreviousFilters(); which is setting the previous filters even after clearing the filters
#### How did you test and verify your work?
Working in storybook

2023-08-23 20:56 UTC, elycheea requested changes
So while this seems to resolve the current bug, I do think this current change has unintended consequences where you are unable to restore the current set of filters in batch mode at all. 

I think it would make more sense to investigate how we’re clearing the filters. Once someone explicitly clears the filters, we may not need to retain the previous filter state.

2023-08-28 05:03 UTC, rakesh-musturi commented
@elycheea Got it, will fix this too

2023-10-18 19:45 UTC, matthewgallo commented
Hey @rakesh-musturi, this should now be fixed as part of  https://github.com/carbon-design-system/ibm-products/pull/3582. If you still see this behavior after the next release, feel free to reach back out!

2023-10-18 19:45 UTC, closed without merging

2023-10-19 04:24 UTC, rakeshmusturi commented
I have read the DCO document and I hereby sign the DCO.