fix(Datagrid): expandable row add background on hover
carbon-design-system/ibm-products pull request #3550
Opened 2023-10-05 19:21 UTC by matthewgallo

Contributes to #3324 

Adds background color to expanded area when hovering on the expanded row.

#### What did you change?
```
packages/ibm-products/src/components/Datagrid/styles/_useExpandedRow.scss
```
#### How did you test and verify your work?
Storybook

2023-10-05 20:14 UTC, elycheea requested changes
If we’re following the row hover behavior from Carbon, I think hover over the expanded area should also show the hover state. Currently only seeing the hover state when hovering over the row itself but not the expanded content.

2023-10-05 20:17 UTC, matthewgallo commented
Ah ok, I must have misread the issue. I'll change this ^

2023-10-06 15:47 UTC, matthewgallo commented
Ended up taking a similar approach to Carbon for highlighting the parent row of the expanded area, couldn't get `:has(+ .expanded-class)` previous sibling selector to work here.

2023-10-06 16:42 UTC, davidmenendez requested changes
looks good. just one small comment.

2023-10-06 16:42 UTC, davidmenendez commented on packages/ibm-products/src/components/Datagrid/Datagrid/DatagridExpandedRow.js
> +        event.target.parentNode.previousElementSibling
i'd do something like this to make this a little less painful
```
const parentNode = event?.target?.parentNode?.previousElementSibling;
if (parentNode)
...
```

2023-10-06 16:51 UTC, davidmenendez approved these changes

2023-10-06 17:32 UTC, davidmenendez approved these changes

2023-10-06 18:24 UTC, elycheea approved these changes

2023-10-06 18:34 UTC, merged