N2p 3489 coachmark a11y
carbon-design-system/ibm-products pull request #3615
Opened 2023-10-16 21:08 UTC by jlongshore

Contributes to [3489](https://github.com/carbon-design-system/ibm-products/issues/3489)

Accessibility review for the Coachmark suite of components. 

#### What did you change?
Minor styling and markup were changed

#### How did you test and verify your work?
Manually checked along with the IBM Accessibility browser plugin

2023-10-16 21:10 UTC, jlongshore commented
I have read the DCO document and I hereby sign the DCO.

2023-10-16 21:11 UTC, jlongshore commented
recheck

2023-10-16 21:36 UTC, jlongshore commented
recheck

2023-10-16 21:44 UTC, jlongshore commented
recheck

2023-10-16 22:00 UTC, jlongshore commented
recheck

2023-10-31 13:30 UTC, paul-balchin-ibm commented on packages/ibm-products/src/components/Coachmark/CoachmarkOverlay.js
> +          {getModifiedChildren()}
`getModifiedChildren()` and `modifyChildren()` are only referenced once each. Can they simply be inlined here?

2023-10-31 13:30 UTC, paul-balchin-ibm commented on packages/ibm-products/src/components/Coachmark/styles/_coachmark-overlay.scss
> +      // padding: $spacing-01 $spacing-05 $spacing-05;
Remove comment.

2023-10-31 13:30 UTC, paul-balchin-ibm commented on packages/ibm-products/src/components/CoachmarkBeacon/_coachmark-beacon.scss
> +        // }
Remove comment.

2023-11-13 18:32 UTC, elycheea commented
@jlongshore is this PR ready for a re-review from @paul-balchin-ibm?

2023-11-13 21:20 UTC, jlongshore commented
> @jlongshore is this PR ready for a re-review from @paul-balchin-ibm?

It should be good to review!

2023-11-14 15:42 UTC, paul-balchin-ibm commented
Reviewing.

2023-11-14 16:16 UTC, paul-balchin-ibm commented on packages/ibm-products/src/components/Coachmark/styles/_coachmark-dragbar.scss
> +    //     &:active {
Delete comments.

2023-11-14 16:16 UTC, paul-balchin-ibm commented on packages/ibm-products/src/components/Coachmark/styles/_coachmark-header.scss
> +    //     &:active {
Delete comments.

2023-11-14 16:20 UTC, paul-balchin-ibm requested changes
Just two "delete comments" requests and a question and we're good to go.

2023-11-14 17:54 UTC, paul-balchin-ibm approved these changes
LGTM 🎉

2023-11-14 20:01 UTC, merged