fix(saving): saving loader alignment
carbon-design-system/ibm-products pull request #4047
Opened 2024-01-12 14:31 UTC by anamikaanu96

Contributes to #3617 

{{Fix alignment of inline loading in save pattern state}}

#### What did you change? 
Added a style in packages/ibm-products-styles/src/components/Saving/_saving.scss 
min-block-size was changed to auto from 2rem
#### How did you test and verify your work? Storybook

2024-01-12 15:36 UTC, elycheea reviewed
Nice! Just need to remove comments we no longer need and to run `yarn format` to address any spacing / line length issues. 🎉

2024-01-12 15:36 UTC, elycheea commented on packages/ibm-products-styles/src/components/Saving/_saving.scss
> +// $carbon-prefix: 'cds';
Looks like you figured out you could use the `carbon-prefix` from settings. :)
We can remove this line now.

2024-01-15 03:58 UTC, anamikaanu96 commented
I have read the DCO document and I hereby sign the DCO.

2024-01-16 21:18 UTC, davidmenendez requested changes
looks good. just need to remove line 15

2024-01-18 14:00 UTC, elycheea approved these changes

2024-01-18 14:48 UTC, merged