feat: update ai-gradient to phase 2 spec
carbon-design-system/ibm-products pull request #4145
Opened 2024-01-24 13:28 UTC by lee-chase

Updates the AI features for Cards and SidePanel to the same level as https://github.com/carbon-design-system/carbon/pull/15528

#### What did you change?
Carbon dependencies.

#### How did you test and verify your work?
Storybook.

2024-01-24 20:13 UTC, matthewgallo requested changes
The `APIKeyModal` has a failing test, appears related to the text being copied to the clipboard

2024-01-25 09:30 UTC, lee-chase commented
> The `APIKeyModal` has a failing test, appears related to the text being copied to the clipboard

That test is failing on the main branch.

2024-01-25 09:58 UTC, lee-chase commented
@matthewgallo looks like the issue was the test relying on the underlying structure of Carbon.

2024-01-25 12:04 UTC, matthewgallo approved these changes

2024-01-25 12:52 UTC, merged