fix(Button menu):button menu accessibility issue - 3519
carbon-design-system/ibm-products pull request #4157
Opened 2024-01-25 09:59 UTC by amal-k-joy

Contributes to #3519 

Follow a11y guideline about "accessible label should contain or match the visible labels) or allow overrides

#### What did you change?
Provide the menuAriaLabel prop to be passed to the Button menu component. This optional label should contain or match the visible labels or it will automatically take button label

#### How did you test and verify your work?
Verified in the storyboard using IBM Equal Access Accessibility Checker.

2024-01-26 15:32 UTC, matthewgallo requested changes
There appear to be some lint issues, running `yarn format` should resolve this for you.

2024-01-29 06:51 UTC, amal-k-joy commented
> There appear to be some lint issues, running `yarn format` should resolve this for you.
@matthewgallo 
I have resolved as advised

2024-01-31 11:19 UTC, Ratheeshrajan reviewed
The accessibility checker requires that the visible text/label match the `area-label`, in my opinion. The addition of the new prop `menuArearLabel` could potentially lead to an accessibility violation. Take a look at this example:
1. Maintain the label on the `Primary button` menu button.
2. Add `menuAreaLabel` something different text
3. Restart the accessibility checker.

In my openion we only need to add `areaLabel={label}` in `ButtonMenu` component.  @matthewgallo could you add your thoughts.

2024-01-31 15:29 UTC, matthewgallo commented
I do like the simplicity of just using the `label` as the `ariaLabel` however, it can be a node which I don't think is a valid value to pass to `aria-label`. You might consider the approach that @devadula-nandan [made recently in the Tearsheet](https://github.com/carbon-design-system/ibm-products/pull/4130/files#diff-b8bde42986b0f2763c922b3e9bfa4f7deb72e4dcfee6731cb498313f9e4c47ecR218) where if there is an ariaLabel prop passed in (in your case menuAriaLabel) we use that, otherwise we try to set it to the text content of the `label` prop since it could be a node.

2024-02-01 06:27 UTC, amal-k-joy commented on packages/ibm-products/src/components/ButtonMenu/ButtonMenu.test.js
> +const menuAriaLabel = `aria ${label} label`;
This variable menuAriaLabel is used to make it consistent with V2 code base.

2024-02-01 09:17 UTC, amal-k-joy commented
> I do like the simplicity of just using the `label` as the `ariaLabel` however, it can be a node which I don't think is a valid value to pass to `aria-label`. You might consider the approach that @devadula-nandan [made recently in the Tearsheet](https://github.com/carbon-design-system/ibm-products/pull/4130/files#diff-b8bde42986b0f2763c922b3e9bfa4f7deb72e4dcfee6731cb498313f9e4c47ecR218) where if there is an ariaLabel prop passed in (in your case menuAriaLabel) we use that, otherwise we try to set it to the text content of the `label` prop since it could be a node.

I have used getNodeTextContent , so that it will either take from menuAriaLabel prop or take the text content of the label.

2024-02-02 14:46 UTC, matthewgallo approved these changes

2024-02-05 14:05 UTC, merged