feat(StringFormatter): new component StringFormatter
carbon-design-system/ibm-products pull request #4249
Opened 2024-02-08 17:27 UTC by jlongshore

Contributes to [issue 4224](https://github.com/carbon-design-system/ibm-products/issues/4224)

Migrate **StringFormatter** from `Products v1 / Security / StringFormatter` to **Products v2** as `StringFormatter`. 

`v1` References: [GitHub](https://github.com/carbon-design-system/ibm-products/blob/main_v1/packages/security/src/components/StringFormatter/StringFormatter.js), [Storybook](https://v1-carbon-for-ibm-products.netlify.app/?path=/docs/security-components-stringformatter--default).

#### What did you change?

- Modified structure slightly to match Products' standards

#### How did you test and verify your work?
- [x] Storybook review.
- [x] Tests migrated and added to.
- [] Design review by Cameron Calder.

2024-02-09 17:27 UTC, davidmenendez requested changes
looks good! have a few comments on the code and one regarding the style

![Screenshot 2024-02-09 at 11 17 21 AM](https://github.com/carbon-design-system/ibm-products/assets/6370760/4a26495d-f692-4e1e-b9ff-85e66406491b)

the `line-height` here seems a bit small? i don't see any design documentation that's accompanying this, so i don't know for certain. this might be nothing, but i just wanted to point out that it looks a bit squished.

2024-02-09 17:27 UTC, davidmenendez commented on packages/ibm-products/src/components/StringFormatter/StringFormatter.js
> +      // The component props, in alphabetical order (for consistency).
same comment as before about cleaning up comments

2024-02-09 17:27 UTC, davidmenendez commented on packages/ibm-products/src/components/StringFormatter/StringFormatter.js
> +          ...rest
prop spreading should always be first in order to avoid the user possibly overwriting them

2024-02-09 17:27 UTC, davidmenendez commented on packages/ibm-products/src/components/StringFormatter/StringFormatter.js
> +let StringFormatterContent = React.forwardRef(
as a general convention we should always separate components into their own files. this seems small enough that i don't think it's strictly _necessary_ to have it's own dedicated file. i think this code could just be lumped back into `StringFormatter`. either way is completely fine.

2024-02-09 21:40 UTC, jlongshore commented
> the `line-height` here seems a bit small? i don't see any design documentation that's accompanying this, so i don't know for certain. this might be nothing, but i just wanted to point out that it looks a bit squished.

Yep, this thing should just inherit the line height, color - that kinda stuff from its parent or be set with a class or something. I think for the stories we just did body-01 type style and a text-primary color

2024-02-15 15:36 UTC, davidmenendez approved these changes

2024-02-15 19:43 UTC, merged