feat(ScrollGradient): new component ScrollGradient
carbon-design-system/ibm-products pull request #4446
Opened 2024-02-27 22:40 UTC by jlongshore

Contributes to [#4309](https://github.com/carbon-design-system/ibm-products/issues/4309)

Migrate **ScrollGradient** from `Products v1 / Security / ScrollGradient` to **Products v2** as `ScrollGradient`. 

`v1` References: [GitHub](https://github.com/carbon-design-system/ibm-products/blob/main_v1/packages/security/src/components/ScrollGradient/ScrollGradient.js), [Storybook](https://v1-carbon-for-ibm-products.netlify.app/?path=/story/security-components-scrollgradient-legacy--vertical-scrolling).

#### What did you change?

- direction prop - removed. Component should manage both horizontal and vertical scrolls. 
- color prop - no longer required - defaults to layout-01

#### How did you test and verify your work?
- [x] Storybook review.
- [x] Tests migrated and added to.
- [x] Design review by Cameron Calder.

2024-03-26 18:42 UTC, davidmenendez requested changes
looks awesome. just 1 small thing

2024-03-26 18:42 UTC, davidmenendez commented on packages/ibm-products/src/components/ScrollGradient/ScrollGradient.js
> +              className={cx(`${blockClass}__start-vertical`)}
`cx` is unnecessary here

2024-03-26 18:42 UTC, davidmenendez commented on packages/ibm-products/src/components/ScrollGradient/ScrollGradient.js
> +              className={cx(`${blockClass}__start-horizontal`)}
`cx` is unnecessary here

2024-03-26 18:42 UTC, davidmenendez commented on packages/ibm-products/src/components/ScrollGradient/ScrollGradient.js
> +          className={cx(`${blockClass}__end-vertical`)}
`cx` is unnecessary here

2024-03-26 18:42 UTC, davidmenendez commented on packages/ibm-products/src/components/ScrollGradient/ScrollGradient.js
> +          className={cx(`${blockClass}__end-horizontal`)}
`cx` is unnecessary here

2024-03-27 11:47 UTC, elycheea reviewed
Also need to remove `story-structure.js` and follow the updated story format.
https://github.com/carbon-design-system/ibm-products/pull/4534

2024-03-29 17:23 UTC, elycheea approved these changes

2024-03-29 17:47 UTC, davidmenendez approved these changes

2024-03-29 20:56 UTC, merged