chore(search-bar): cleaned up props
carbon-design-system/ibm-products pull request #4923
Opened 2024-04-17 07:30 UTC by IgnacioBecerra

Contributes to #4602

This PR cleans up the SearchBar props that were mentioned [here](https://github.com/carbon-design-system/ibm-products/issues/4239#issuecomment-1965282111). Groups up MultiSelect props for adopter ease of use. 

#### What did you change?
`placeHolderText` -> `placeholderText` (changed upper to lower case `h`)

#### How did you test and verify your work?
Changes work in my local Storybook instance

2024-04-22 16:40 UTC, davidmenendez requested changes
aside from the lint error just one small comment

2024-04-22 16:40 UTC, davidmenendez commented on packages/ibm-products/src/components/SearchBar/SearchBar.js
> +      ...rest
i don't think the rest here is necessary

2024-04-29 22:20 UTC, IgnacioBecerra commented
@davidmenendez Sorry for the wait! I was busy fixing a problem we've had in Dotcom for a while. Let me know if there's anything else so we can get this merged!

2024-04-30 20:24 UTC, matthewgallo commented
@IgnacioBecerra there are some failing `SearchBar` tests now, see [here](https://github.com/carbon-design-system/ibm-products/actions/runs/8886189184/job/24399179313?pr=4923#step:6:242).

2024-05-07 18:54 UTC, davidmenendez approved these changes

2024-05-13 22:21 UTC, merged