refactor(editupdatecards): add typescript types
carbon-design-system/ibm-products pull request #4994
Opened 2024-04-29 13:12 UTC by szinta

Contributes to #4286 

Add typescript types to EditUpdateCards component

#### What did you change?
packages/ibm-products/src/components/EditUpdateCards/EditUpdateCards.tsx

#### How did you test and verify your work?
Storybook

2024-04-30 20:05 UTC, matthewgallo commented on packages/ibm-products/src/components/EditUpdateCards/EditUpdateCards.tsx
> +  actionIcons: Array<ActionIcon>;
Should be optional
```suggestion
  actionIcons?: Array<ActionIcon>;
```

2024-04-30 20:05 UTC, matthewgallo commented on packages/ibm-products/src/components/EditUpdateCards/EditUpdateCards.tsx
> +  editChildren: ReactNode;
Should be optional
```suggestion
  editChildren?: ReactNode;
```

2024-04-30 20:06 UTC, matthewgallo commented on packages/ibm-products/src/components/EditUpdateCards/EditUpdateCards.tsx
> +  previewChildren: ReactNode;
Should be optional
```suggestion
  previewChildren?: ReactNode;
```

2024-04-30 20:08 UTC, matthewgallo requested changes
Just found a few props that should be updated as optional as specified in the prop types, other than that looks great.

2024-05-02 05:49 UTC, szinta commented
Thanks @matthewgallo for the review. I've applied the suggested changes. Please take a look again.

2024-05-06 17:04 UTC, matthewgallo approved these changes

2024-05-06 17:10 UTC, merged