refactor(TagSet): add typescript types
carbon-design-system/ibm-products pull request #5104
Opened 2024-05-08 06:59 UTC by anamikaanu96

Contributes to #4503 , #5102 , #5103 

Converted the below files from js to tsx
[]packages/ibm-products/src/components/TagSet/TagSet.js to packages/ibm-products/src/components/TagSet/TagSet.tsx
[]packages/ibm-products/src/components/TagSet/TagSetModal.js to packages/ibm-products/src/components/TagSet/TagSetModal.tsx
[]packages/ibm-products/src/components/TagSet/TagSetOverflow.js to packages/ibm-products/src/components/TagSet/TagSetOverflow.tsx

#### What did you change?  
packages/ibm-products/src/components/TagSet/TagSet.tsx 
packages/ibm-products/src/components/TagSet/TagSetModal.tsx
packages/ibm-products/src/components/TagSet/TagSetOverflow.tsx

#### How did you test and verify your work? Storybook

2024-05-09 13:59 UTC, amal-k-joy requested changes

2024-05-13 10:34 UTC, anamikaanu96 commented
All the reviewed changed are resolved @amal-k-joy.

2024-05-13 11:33 UTC, amal-k-joy commented
> All the reviewed changed are resolved @amal-k-joy.

Looks good.
Thanks

2024-05-13 11:34 UTC, amal-k-joy approved these changes
Looks good.
Thanks

2024-05-13 11:41 UTC, merged