test(APIKeyModal): add default state AVT check
carbon-design-system/ibm-products pull request #5111
Opened 2024-05-08 11:13 UTC by makafsal

Contributes to #4661 

#### What did you change?
Create file: `e2e/components/APIKeyModal/APIKeyModal-test.avt.e2e.js`

#### How did you test and verify your work?
`yarn avt`

2024-05-09 16:31 UTC, davidmenendez approved these changes

2024-05-09 17:00 UTC, matthewgallo requested changes
This is another case where you have to click the button on the story page in order for the modal to be visible before running the a11y check.

2024-05-13 12:13 UTC, amal-k-joy requested changes
Looks fine

2024-05-13 13:21 UTC, matthewgallo approved these changes

2024-05-13 13:28 UTC, merged