feat(Guidebanner): convert to .tsx
carbon-design-system/ibm-products pull request #5141
Opened 2024-05-09 19:37 UTC by paul-balchin-ibm

Contributes to #4487, #4488, #4489, #4490

This PR converts `Guidebanner`, `GuidebannerElement`, `GuidebannerElementButton`, and `GuidebannerElementLink`  to TypeScript.

#### What did you change?

- file extension
- TS interface

#### How did you test and verify your work?

storybook build and type checks

2024-05-16 19:24 UTC, annawen1 approved these changes
LGTM

2024-05-22 19:30 UTC, matthewgallo commented on packages/ibm-products/src/components/Guidebanner/GuidebannerElement.tsx
> +  description: string | ReactNode;
I believe `string` is also considered a `ReactNode` so you could just specify `description: ReactNode`
```suggestion
  description: ReactNode;
```

2024-05-22 19:32 UTC, matthewgallo commented on packages/ibm-products/src/components/Guidebanner/GuidebannerElementButton.tsx
> +          iconDescription={'Crossroads'}
Can you update this so it's not a hard coded string? This component might need a new prop, `iconDescription`

2024-05-22 19:34 UTC, matthewgallo requested changes
Just had two comments regarding `string` and `ReactNode` and a hardcoded string in `GuideBannerElementButton`

2024-05-23 13:31 UTC, paul-balchin-ibm commented
Closing. Made changes, merged latest, push was rejected, _followed git instructions to fix_, now have other people's gazillion changes.

Please see replacement PR #5321

2024-05-23 13:31 UTC, closed without merging