refactor(EditTearsheetForm): add Typescript types
carbon-design-system/ibm-products pull request #5167
Opened 2024-05-13 22:35 UTC by IgnacioBecerra

Closes [#4283](https://github.com/carbon-design-system/ibm-products/issues/4283)

This PR introduces Typescript types to EditTearsheetForm

#### What did you change?
Changed the file and component to using Typescript

#### How did you test and verify your work?
Ran tests and build locally

2024-05-14 15:42 UTC, matthewgallo commented on packages/ibm-products/src/components/EditTearsheet/EditTearsheetForm.tsx
> +    const formContext = useContext(FormContext) as any;
You could avoid using `any` here if you provide a type that is shared between when this context is created in `EditTearsheet` and then here as well.
```
export const FormContext = createContext<FormContextType | null>(null);
```

```
const formContext = useContext(FormContext) as FormContextType;
```

where `FormContextType` could be something like
```
type FormContextType = {
  currentForm: number;
  setFormTitle: () => void;
};
```

2024-05-14 15:43 UTC, matthewgallo commented on packages/ibm-products/src/components/EditTearsheet/EditTearsheetForm.tsx
> +  subtitle: string;
This should be optional
```suggestion
  subtitle?: string;
```

2024-06-04 14:38 UTC, amal-k-joy requested changes

2024-06-07 21:00 UTC, IgnacioBecerra commented on packages/ibm-products/src/components/EditTearsheet/EditTearsheet.js
> +export const FormContext = (createContext < FormContext) | (null > null);
Hey Amal, you're right, but I'd like to export the FormContextType from EditTearsheet.tsx, which will be introduced in #5082, wondering if we can get that in first?

2024-06-19 22:38 UTC, IgnacioBecerra commented on packages/ibm-products/src/components/EditTearsheet/EditTearsheet.js
> +export const FormContext = (createContext < FormContext) | (null > null);
Should be fixed now!

2024-06-25 13:26 UTC, amal-k-joy approved these changes

2024-06-25 13:30 UTC, matthewgallo approved these changes

2024-06-25 13:37 UTC, merged