test(CreateSidePanel): add default state AVT test
carbon-design-system/ibm-products pull request #5247
Opened 2024-05-16 08:43 UTC by anamikaanu96

Closes #4663 

Created e2e/components/CreateSidePanel/CreateSidePanel-test.avt.e2e.js

#### What did you change? e2e/components/CreateSidePanel/CreateSidePanel-test.avt.e2e.js

#### How did you test and verify your work? yarn avt

2024-05-16 14:51 UTC, emyarod reviewed
it looks like the avt suite is still timing out for some reason, even after rerunning

https://github.com/carbon-design-system/ibm-products/actions/runs/9109254784/job/25041736070?pr=5247
https://github.com/carbon-design-system/ibm-products/actions/runs/9109254784/job/25055608101?pr=5247

2024-05-17 20:55 UTC, IgnacioBecerra requested changes
Other than my comment, everything seems good, not sure why the runner is failing like Andrew mentioned but otherwise things do look good.

2024-05-17 20:55 UTC, IgnacioBecerra commented on cspell.json
> +    "createsidepanel",
```suggestion
```
We don't need to add any files to the cspell file, as #5202 takes care of the avt files.

2024-05-21 13:28 UTC, annawen1 approved these changes
LGTM!

2024-05-21 13:36 UTC, ariellalgilmore approved these changes
LGTM!

2024-05-21 13:39 UTC, elycheea approved these changes

2024-05-21 14:17 UTC, merged