test(NotificationsEmptyState): added default state AVT test
carbon-design-system/ibm-products pull request #5265
Opened 2024-05-17 19:04 UTC by IgnacioBecerra

Closes #5073

#### What did you change?

added the avt test file for the component

#### How did you test and verify your work?
ran `yarn avt`

2024-05-20 09:06 UTC, amal-k-joy requested changes

2024-05-20 09:06 UTC, amal-k-joy commented on cspell.json
> +    "notificationsemptystate",
Hey,
We don't need to add here as all .avt files have already excluded from spell check.
` "ignorePaths": [
...,
    "*.avt.e2e.js",` ...]

2024-05-21 19:22 UTC, annawen1 approved these changes

2024-05-22 08:38 UTC, amal-k-joy approved these changes

2024-05-22 08:46 UTC, merged