feat(AddSelect): add dynamic additional component at start of body
carbon-design-system/ibm-products pull request #5438
Opened 2024-06-07 19:11 UTC by glapadre

Closes #5252 

Add custom component option at the beginning of the Body (in our case we are using TextInput but it could be anything here.

#### What did you change?

#### How did you test and verify your work?
Storybook

2024-06-11 15:45 UTC, davidmenendez requested changes
@glapadre thanks for providing this! Two things;

one minor code comment: can we switch `additionalInfo` to `supplementalHeader`? i think that helps convey what the prop does.

i know theres a greater discussion at hand about the add/select structure, so i don't think this needs a whole DSAG intervention, but could you find a designer associated with add/select to sign off on this? i think the story could look a little nicer and better describe what the feature is. working with someone on the design side just to establish like a minimal requirement for this part of the pattern would be great.

if you have any questions holler at me!

2024-06-11 15:49 UTC, glapadre commented
@davidmenendez no problem! I started a thread in the [issue](https://github.com/carbon-design-system/ibm-products/issues/5252) related to naming convention but it didn't get any traction, `supplementalHeader` works well.. I'll reach out to the design lead for Add Select and get approval and work on the story

2024-06-13 13:38 UTC, davidmenendez commented
@glapadre awesome! thanks. keep me up to date 👍

2024-06-13 14:06 UTC, glapadre commented
@davidmenendez I have shared with Oliver Kauselmann (designer that worked on add/select) and he said he will take a look and share here

2024-06-17 17:11 UTC, davidmenendez commented
@glapadre awesome! thanks a bunch

2024-06-21 15:17 UTC, glapadre commented
Had a call with Marion H. and Oliver K. and we are working on updating the guidance on the PAL design site, once this is complete Marion and Oliver gave the green light to merge.

2024-08-12 13:02 UTC, davidmenendez commented
@glapadre any update on this?

2026-02-17 07:36 UTC, amal-k-joy commented
@glapadre 

Do you think we can merge this or close this?

2026-02-20 16:42 UTC, glapadre commented
@amal-k-joy the issue attached to this PR was closed back in Dec 2024

2026-05-15 09:47 UTC, closed without merging