refactor(useExpandedRow): add typescript types
carbon-design-system/ibm-products pull request #5489
Opened 2024-06-13 12:18 UTC by szinta

Closes #5180 

Add Typescript types to useExpandedRow

#### What did you change?
Changed `packages/ibm-products/src/components/Datagrid/useExpandedRow.js `to `packages/ibm-products/src/components/Datagrid/useExpandedRow.ts`

#### How did you test and verify your work?

- Storybook
- Yarn test

2024-06-13 16:32 UTC, matthewgallo commented on packages/ibm-products/src/components/Datagrid/types/index.ts
> +  expandedContentHeight?: boolean;
This should be `number`

2024-06-13 16:33 UTC, matthewgallo requested changes
See comment regarding type of `expandedContentHeight`

2024-06-14 12:44 UTC, matthewgallo approved these changes

2024-06-17 05:49 UTC, devadula-nandan approved these changes

2024-06-17 06:10 UTC, merged