fix(datagrid): check tableId before triggering reset of filters
carbon-design-system/ibm-products pull request #5546
Opened 2024-06-19 18:09 UTC by annawen1

Closes #4523 

When there are multiple instances of Datagrid used, clicking the "clear filters" in one DataGrid instance causes all DataGrid filters to be reset instead of the specific instance.

This PR passes the `tableId` of the DataGrid to its Filter Context and is then compared and must match before resetting the filters.

#### What did you change?

#### How did you test and verify your work?

2024-06-19 18:24 UTC, matthewgallo requested changes
💯 this is great!

Can you also update the `useSubscribeToEventEmitter` hook in `FilterPanel.js` as well to include these same updates?

2024-06-19 20:40 UTC, annawen1 commented
> 💯 this is great!
> 
> Can you also update the `useSubscribeToEventEmitter` hook in `FilterPanel.js` as well to include these same updates?

Oop! yeah good catch!

2024-06-20 20:36 UTC, matthewgallo approved these changes

2024-06-21 08:50 UTC, makafsal approved these changes
Looks good.

2024-06-21 09:04 UTC, merged