test(CreateFullPage): add AVT test for error and disabled state
carbon-design-system/ibm-products pull request #5627
Opened 2024-07-01 12:06 UTC by anamikaanu96

Closes #5525 

Add test for error state and disabled state

#### What did you change? `e2e/components/CreateFlows/CreateFullPage-test.avt.e2e.js`

#### How did you test and verify your work? `yarn avt`

2024-07-02 05:13 UTC, amal-k-joy requested changes

2024-07-02 05:13 UTC, amal-k-joy commented on e2e/components/CreateFlows/CreateFullPage-test.avt.e2e.js
> +    const isBackDisabled = await backButtonElement.isDisabled();
Hey, I think by default the input box is will be empty always and dataInvalid will be true.
After checking the invalid state and disabled state, can we add some text to the input filed to test  valid state and next button enabled state as-well.

2024-07-02 09:38 UTC, amal-k-joy requested changes

2024-07-02 09:38 UTC, amal-k-joy commented on e2e/components/CreateFlows/CreateFullPage-test.avt.e2e.js
> +    await expect(isBackDisabledNow).toBe(true);
Can you add this as well at the end
const dataInvalid = await inputElement.getAttribute('data-invalid');
await expect(dataInvalid).toBe('false');

2024-07-03 05:57 UTC, amal-k-joy approved these changes
Looks good

2024-07-08 19:31 UTC, matthewgallo approved these changes

2024-07-08 19:40 UTC, merged