test(TearsheetNarrow): AVT tests for complex states
carbon-design-system/ibm-products pull request #5644
Opened 2024-07-05 05:06 UTC by makafsal

Closes #5522

#### What did you change?
`e2e/components/Tearsheet/TearsheetNarrow-test.avt.e2e.js`

#### How did you test and verify your work?
yarn avt

2024-07-08 10:32 UTC, amal-k-joy requested changes
Looks good

2024-07-08 12:36 UTC, makafsal commented on e2e/components/Tearsheet/TearsheetNarrow-test.avt.e2e.js
> +    await expect(modalElement).not.toBeInViewport();
In the DOM element is not changing, only attributes and classes are changing. So the `modalElement` always refer the same DOM element.

2024-07-10 13:04 UTC, amal-k-joy approved these changes

2024-07-10 19:54 UTC, elycheea approved these changes

2024-07-10 20:04 UTC, merged