refactor(EmptyState): add types to EmptyState
carbon-design-system/ibm-products pull request #5711
Opened 2024-07-22 20:50 UTC by annawen1

Closes #

{{short description}}

#### What did you change?

#### How did you test and verify your work?

2024-07-29 18:46 UTC, davidmenendez commented
@annawen1 looks like we have a conflict because this morning the v2 typescript refactor was merged https://github.com/carbon-design-system/ibm-products/pull/5747 which was a separate issue. oops! haha

2024-07-30 15:18 UTC, matthewgallo approved these changes

2024-07-30 19:57 UTC, davidmenendez approved these changes

2024-07-30 20:07 UTC, merged

2024-07-30 20:08 UTC, AlexanderMelox requested changes

2024-07-30 20:08 UTC, AlexanderMelox commented on packages/ibm-products/src/components/EmptyStates/EmptyStateV2.tsx
> +    text?: string | ReactNode;
```suggestion
    text?: ReactNode;
```