chore: tagoverflow typescript conversion
carbon-design-system/ibm-products pull request #5715
Opened 2024-07-23 19:40 UTC by davidmenendez

Closes #5673

2024-07-25 06:02 UTC, amal-k-joy requested changes
Good work 
Please see some minor comments

2024-07-25 06:02 UTC, amal-k-joy commented on packages/ibm-products/src/components/TagOverflow/TagOverflowPopover.tsx
> +    const hasItems = visibleItems && visibleItems?.length > 0;
same comment as above
`const hasItems = visibleItems?.length > 0;`

2024-07-30 14:43 UTC, amal-k-joy approved these changes

2024-07-30 15:12 UTC, matthewgallo commented on packages/ibm-products/src/components/TagOverflow/TagOverflow.tsx
> +  tagType?:
If possible we should try to import this from `@carbon/react`.

2024-07-30 15:13 UTC, matthewgallo approved these changes
Found some types that we might be able to just pull in from `@carbon/react`, but we can open a separate issue.

2024-07-30 15:22 UTC, merged