refactor(Card): convert to typescript
carbon-design-system/ibm-products pull request #5760
Opened 2024-07-30 07:50 UTC by anamikaanu96

Closes #5197 

Add Typescript types to Card, CardFooter, CardHeader

#### What did you change? 
Converted below files : 
packages/ibm-products/src/components/Card/Card.js to packages/ibm-products/src/components/Card/Card.tsx
packages/ibm-products/src/components/Card/CardHeader.js to packages/ibm-products/src/components/Card/CardHeader.tsx
packages/ibm-products/src/components/Card/CardFooter.js to packages/ibm-products/src/components/Card/CardFooter.tsx

#### How did you test and verify your work? storybook

2024-07-30 12:01 UTC, amal-k-joy requested changes

2024-07-30 15:21 UTC, matthewgallo requested changes
There seems to be a type error with `footerActionIcon`

https://github.com/carbon-design-system/ibm-products/actions/runs/10164871770/job/28111339889?pr=5760

2024-07-30 19:59 UTC, davidmenendez requested changes
LGTM just one small comment

2024-07-30 19:59 UTC, davidmenendez commented on packages/ibm-products/src/components/Card/Card.tsx
> +// const defaults = {
can you remove these commented out defaults?

2024-07-31 18:55 UTC, davidmenendez submitted a review, later dismissed
LGTM

2024-07-31 19:50 UTC, AlexanderMelox requested changes

2024-07-31 19:50 UTC, AlexanderMelox commented on packages/ibm-products/src/components/Card/Card.tsx
> +  title?: string | ReactNode;
```suggestion
  title?: ReactNode;
```
ReactNode supports string, no need to add it here

2024-07-31 19:50 UTC, AlexanderMelox commented on packages/ibm-products/src/components/Card/Card.tsx
> +  description?: string | ReactNode;
```suggestion
  description?: ReactNode;
```

2024-07-31 19:50 UTC, AlexanderMelox commented on packages/ibm-products/src/components/Card/CardHeader.tsx
> +  description?: string | ReactNode;
```suggestion
  description?: ReactNode;
```

2024-07-31 19:50 UTC, AlexanderMelox commented on packages/ibm-products/src/components/Card/CardHeader.tsx
> +  label?: string | ReactNode;
```suggestion
  label?: ReactNode;
```

2024-07-31 19:50 UTC, AlexanderMelox commented on packages/ibm-products/src/components/Card/CardHeader.tsx
> +  title?: string | ReactNode;
```suggestion
  title?: ReactNode;
```

2024-07-31 19:50 UTC, AlexanderMelox commented on packages/ibm-products/src/components/GetStartedCard/GetStartedCard.tsx
> +  label?: string | ReactNode;
```suggestion
  label?: ReactNode;
```

2024-07-31 19:50 UTC, AlexanderMelox commented on packages/ibm-products/src/components/GetStartedCard/GetStartedCard.tsx
> +  title?: string | ReactNode;
```suggestion
  title?: ReactNode;
```

2024-08-01 09:51 UTC, amal-k-joy approved these changes

2024-08-01 13:47 UTC, AlexanderMelox approved these changes

2024-08-01 13:58 UTC, matthewgallo approved these changes

2024-08-01 14:07 UTC, merged