feat(typescript): update generate scripts to use ts
carbon-design-system/ibm-products pull request #5817
Opened 2024-08-06 19:54 UTC by AlexanderMelox

Closes #4627 

This PR updates the generate script to output Typescript components when generating new components. I also refactor the generate script itself to add the typescript props exports to `index.ts`. `index.ts` does not exist on this PR but it is being added in https://github.com/carbon-design-system/ibm-products/pull/5807.

#### What did you change?
- packages/ibm-products/scripts/generate/index.js
- 

#### How did you test and verify your work?
By running `yarn generate TestComponent`

2024-08-13 19:13 UTC, matthewgallo requested changes

2024-08-13 19:13 UTC, matthewgallo commented on packages/ibm-products/scripts/generate/templates/DISPLAY_NAME.tsx
>      ref
Adding the following will get rid of a ts error from the forwarded ref

```
ref: ForwardedRef<HTMLDivElement>
```

![image](https://github.com/user-attachments/assets/033ad40f-d1d0-4b87-8c95-add44e4e462f)

2024-08-14 18:12 UTC, matthewgallo approved these changes

2024-08-14 18:54 UTC, davidmenendez approved these changes

2024-08-14 19:03 UTC, merged