Conditionbuilder typescript
carbon-design-system/ibm-products pull request #5841
Opened 2024-08-09 08:49 UTC by amal-k-joy

Closes #5670 

Typescript migration for condition builder

#### What did you change?
```

1. packages/ibm-products/src/components/ConditionBuilder/ConditionBuilder.types.ts
2. packages/ibm-products/src/components/ConditionBuilder/ConditionBlock/ConditionBlock.tsx
3. packages/ibm-products/src/components/ConditionBuilder/ConditionBuilder.tsx
4. packages/ibm-products/src/components/ConditionBuilder/ConditionBuilderActions/ConditionBuilderActions.tsx
5. packages/ibm-products/src/components/ConditionBuilder/ConditionBuilderAdd/ConditionBuilderAdd.tsx
6. packages/ibm-products/src/components/ConditionBuilder/ConditionBuilderButton/ConditionBuilderButton.tsx
7. packages/ibm-products/src/components/ConditionBuilder/ConditionBuilderConnector/ConditionConnector.tsx
8. packages/ibm-products/src/components/ConditionBuilder/ConditionBuilderContent/ConditionBuilderContent.tsx
9. packages/ibm-products/src/components/ConditionBuilder/ConditionBuilderContext/ConditionBuilderProvider.tsx
10. packages/ibm-products/src/components/ConditionBuilder/ConditionBuilderItem/ConditionBuilderItem.tsx
11. packages/ibm-products/src/components/ConditionBuilder/ConditionBuilderItem/ConditionBuilderItemDate/ConditionBuilderItemDate.tsx
12. packages/ibm-products/src/components/ConditionBuilder/ConditionBuilderItem/ConditionBuilderItemNumber/ConditionBuilderItemNumber.tsx
13. packages/ibm-products/src/components/ConditionBuilder/ConditionBuilderItem/ConditionBuilderItemOption/ItemOption.tsx
14. packages/ibm-products/src/components/ConditionBuilder/ConditionBuilderItem/ConditionBuilderItemOption/ItemOptionForValueField.tsx
15. packages/ibm-products/src/components/ConditionBuilder/ConditionBuilderItem/ConditionBuilderItemText/ConditionBuilderItemText.tsx
16. packages/ibm-products/src/components/ConditionBuilder/ConditionBuilderItem/ConditionBuilderItemTime/ConditionBuilderItemTime.tsx
17. packages/ibm-products/src/components/ConditionBuilder/ConditionGroupBuilder/ConditionGroupBuilder.tsx
18. packages/ibm-products/src/components/ConditionBuilder/ConditionPreview/ConditionPreview.tsx

```
#### How did you test and verify your work?
TS error and storybook

2024-08-14 18:02 UTC, AlexanderMelox requested changes

2024-08-14 18:53 UTC, davidmenendez requested changes
agreed with @AlexanderMelox

2024-08-19 07:12 UTC, amal-k-joy commented on packages/ibm-products/src/components/ConditionBuilder/ConditionBlock/ConditionBlock.tsx
> +  onRemove: (e: any) => void;
Hey,
I have made the changes

2024-08-19 07:12 UTC, amal-k-joy commented on packages/ibm-products/src/components/ConditionBuilder/ConditionBuilderButton/ConditionBuilderButton.tsx
> +  //onFocus:any,
Hey,
I have made the changes

2024-08-19 07:12 UTC, amal-k-joy commented on packages/ibm-products/src/components/ConditionBuilder/ConditionBuilderButton/ConditionBuilderButton.tsx
> +  onClick?: (e: any) => void;
Hey,
I have made the changes

2024-08-19 16:14 UTC, AlexanderMelox approved these changes

2024-08-19 18:13 UTC, davidmenendez approved these changes

2024-08-20 04:12 UTC, merged