fix(TagSet): fix string formatting
carbon-design-system/ibm-products pull request #5880
Opened 2024-08-16 01:42 UTC by devadula-nandan

Closes #5854 

fixes string format for the child of the `<Tag>` component, which fixes the title attribute.

#### What did you change?
packages/ibm-products/src/components/TagSet/TagSetOverflow.tsx

#### How did you test and verify your work?
storybook

2024-08-16 13:41 UTC, davidmenendez requested changes

2024-08-16 13:41 UTC, davidmenendez commented on packages/ibm-products/src/components/TagSet/TagSetOverflow.tsx
> +            {'+' + overflowTags.length}
would prefer to just use template strings here
```
{`+${overflowTags.length}`}
```

2024-08-16 23:06 UTC, davidmenendez approved these changes

2024-08-19 06:03 UTC, sangeethababu9223 approved these changes
LGTM!

2024-08-20 13:39 UTC, merged