feat: call onClearFilters when clearing filters from tag summary
carbon-design-system/ibm-products pull request #5892
Opened 2024-08-19 21:17 UTC by xmannyxfreshx1

Closes https://github.com/carbon-design-system/ibm-products/issues/5879

support passing a callback function to the filter prop `onClearFilters`. Then if it's not undefined and a function, call it when clicking the 'Clear filters' button in the filter summary component.

#### What did you change?
```
packages/ibm-products/src/components/Datagrid/Datagrid/DatagridContent.tsx
packages/ibm-products/src/components/Datagrid/types/index.ts
```

#### How did you test and verify your work?
Storybook

2024-08-21 10:00 UTC, devadula-nandan requested changes
Thanks for the contribution @xmannyxfreshx1,
could you update the story docs, by mentioning this callback usage?
The code looks good to me.

2024-08-21 10:18 UTC, devadula-nandan requested changes

2024-08-21 10:18 UTC, devadula-nandan commented on packages/ibm-products/src/components/Datagrid/Datagrid/DatagridContent.tsx
> +            typeof filterProps?.onClearFilters !== 'undefined' &&
I think this is not necessary.
``` suggestion
```

2024-08-27 19:53 UTC, xmannyxfreshx1 commented
@devadula-nandan Thanks for the feedback, I've made your suggested changes.

2024-08-29 08:51 UTC, devadula-nandan approved these changes
LGTM

2024-09-05 09:41 UTC, anamikaanu96 approved these changes
Hey @xmannyxfreshx1 Thank you for your contribution! 
The code looks fine. Approved. 🎉

2024-09-05 19:19 UTC, merged