fix(ToolbarButton): deprecate iconDescription and use label instead
carbon-design-system/ibm-products pull request #5893
Opened 2024-08-20 06:30 UTC by makafsal

Closes #5699 

#### What did you change?
Deprecated `iconDescription`, and included `label` prop

#### How did you test and verify your work?
Storybook

2024-08-20 18:47 UTC, davidmenendez requested changes
i think we need to follow the deprecation model happening in [EditInPlace](https://github.com/carbon-design-system/ibm-products/blob/main/packages/ibm-products/src/components/EditInPlace/EditInPlace.tsx#L142) in order to avoid breaking changes. @matthewgallo what do you think?

2024-08-21 15:53 UTC, matthewgallo commented
I agree, we should reassign `iconDescription` to `deprecated_iconDescription` and use `label ?? deprecated_iconDescription`. I do see the jsdoc `@deprecated` tag but better to not include any breaking changes.

2024-08-22 18:55 UTC, davidmenendez approved these changes

2024-08-23 14:51 UTC, AlexanderMelox approved these changes
LGTM

2024-08-23 15:00 UTC, merged