fix(tearsheet): Firefox focuses Tearsheet content div with scroll
carbon-design-system/ibm-products pull request #5973
Opened 2024-08-29 07:00 UTC by makafsal

Closes #5745 

#### What did you change?
`tabIndex: -1` for `div.c4p--tearsheet__content` element

#### How did you test and verify your work?
`yarn avt`
Storybook

2024-09-05 15:47 UTC, matthewgallo approved these changes

2024-09-06 16:38 UTC, davidmenendez requested changes

2024-09-06 16:38 UTC, davidmenendez commented on packages/ibm-products/src/components/Tearsheet/TearsheetShell.tsx
> +                      tabIndex: -1,
instead of trying to bypass the typescript check here i think we should just include `tabIndex` in the type definition

2024-09-10 20:40 UTC, davidmenendez approved these changes

2024-09-11 13:10 UTC, matthewgallo approved these changes

2024-09-11 13:19 UTC, merged