fix(CreateFullPage): header height to work properly on older browsers
carbon-design-system/ibm-products pull request #5993
Opened 2024-09-02 14:39 UTC by baraaabdelsalam

Closes #5992

Fixes the header height issues that showed up in some older browsers

#### What did you change?
Modify some CSS code to ensure broader compatibility

#### How did you test and verify your work?
Manually on different browsers on MacOS

2024-09-03 05:29 UTC, makafsal approved these changes
Looks good.

2024-09-09 06:03 UTC, makafsal approved these changes

2024-09-10 04:26 UTC, amal-k-joy requested changes

2024-09-10 04:26 UTC, amal-k-joy commented on packages/ibm-products-styles/src/__tests__/__snapshots__/styles.test.js.snap
> +  grid-template-rows: auto minmax(min-content, 100%);
Hey @baraaabdelsalam ,
Looks like there is a height/scroll issue with this change. At smaller viewport heights, the footer buttons section need to be fixed and inner content has to scrollable which is not happening now. 
![image](https://github.com/user-attachments/assets/d3c9ad84-5c03-441d-a49d-f3edb8e103d7)

2025-02-14 05:05 UTC, amal-k-joy commented
Closing due to inactivity. Please feel free to reopen if required.

2025-02-14 05:05 UTC, closed without merging