fix: add floating ui to tagset
carbon-design-system/ibm-products pull request #6005
Opened 2024-09-04 21:39 UTC by davidmenendez

Closes #5407 and also #5354

i'm guessing something changed on the carbon side because using floating ui and `autoAlign` is now working with `TagSet`.

the results i'm seeing today are much different (working) compared to a previous attempt to implement. i just reused the same code from a previous PR https://github.com/carbon-design-system/ibm-products/pull/5406

verification of functionality inside the `TagSet` story

<img width="950" alt="Screenshot 2024-09-04 at 4 31 09 PM" src="https://github.com/user-attachments/assets/0285bf04-804e-4bea-9b53-3080d2a89a5f">

verification of functionality using the example code provided in the issue

<img width="1840" alt="Screenshot 2024-09-04 at 4 39 23 PM" src="https://github.com/user-attachments/assets/7ef9d4da-6bb5-45eb-94a4-f9ba49d9b240">

2024-09-06 07:57 UTC, szinta approved these changes
LGTM

2024-09-06 14:08 UTC, matthewgallo requested changes
Can we just change the casing of `overFlowAutoAlign` to `overflowAutoAlign` to match the other `overflow` props?

2024-09-06 16:00 UTC, davidmenendez commented
@matthewgallo that was dumb of me! fixt 😅

2024-09-06 16:01 UTC, matthewgallo approved these changes
🎉

2024-09-09 16:20 UTC, AlexanderMelox approved these changes

2024-09-09 16:29 UTC, merged