fix(datagrid): batch no longer updates filter tag
carbon-design-system/ibm-products pull request #6031
Opened 2024-09-10 17:30 UTC by AlexanderMelox

Closes #5717 

Fixes the issue where the filter tags were updating instantly when using batch actions

#### What did you change?
I changed the filter context state dispatch from useFilters to onApply button callback in the filter panel and filter flyout

#### How did you test and verify your work?
https://github.com/user-attachments/assets/2d590a2a-519c-48fc-8f86-def5fb21e935

2024-09-11 13:38 UTC, matthewgallo approved these changes

2024-09-13 09:43 UTC, amal-k-joy requested changes
Changes look good., but I am seeing a weird behaviour for the date range fileds in our deploy preview, not sure this is related to the changes. 

Uploading Screen Recording 2024-09-13 at 3.09.42 PM.mov…

2024-09-17 16:48 UTC, davidmenendez approved these changes

2024-09-17 16:50 UTC, davidmenendez commented
@amal-k-joy that looks like that might be a separate bug. can you document that behavior in a new issue? thanks!

2024-09-18 05:07 UTC, amal-k-joy commented
> @amal-k-joy that looks like that might be a separate bug. can you document that behavior in a new issue? thanks!

Looks like the issue was from carbon and got resolved now

2024-09-18 05:08 UTC, amal-k-joy approved these changes

2024-09-18 05:17 UTC, merged