fix(dataGrid): focus loss on radio select
carbon-design-system/ibm-products pull request #6073
Opened 2024-09-18 11:33 UTC by devadula-nandan

Closes #5683 

returns the radio select focus, if it's lost.

#### What did you change?
packages/ibm-products/src/components/Datagrid/useSelectRows.tsx

#### How did you test and verify your work?
storybook, screen reader for mac, jaws for win 11

2024-09-23 15:29 UTC, matthewgallo requested changes

2024-09-23 15:29 UTC, matthewgallo commented on packages/ibm-products/src/components/Datagrid/useSelectRows.tsx
> +    const activeElement = document.activeElement?.id ?? '';
Gotta be careful to watch out for SSR apps where document will be `undefined`. You could add an optional chain here or save the active element in a ref from `useIsomorphicEffect`.

2024-09-25 14:00 UTC, amal-k-joy approved these changes
LGTM

2024-09-25 17:58 UTC, matthewgallo approved these changes

2024-09-25 18:07 UTC, merged