refactor(sidepanel): change slug to aiLabel
carbon-design-system/ibm-products pull request #6203
Opened 2024-10-10 12:11 UTC by makafsal

Closes #6095 

#### What did you change?
`slug` to `aiLabel`

#### How did you test and verify your work?
storybook

2024-10-16 15:38 UTC, elycheea requested changes
Instead of replacing `slug`, I believe the cross-squad decision was to duplicate classnames rather than only replacing them.

2024-10-16 15:38 UTC, elycheea commented on packages/ibm-products-styles/src/components/SidePanel/_side-panel.scss
> +  &.#{$block-class}.#{$block-class}--has-ai-label {
I believe the decision was to include _duplicate_ selectors[^1] to be backwards compatible.

```suggestion
  &.#{$block-class}.#{$block-class}--has-slug,
  &.#{$block-class}.#{$block-class}--has-ai-label {
```

[^1]: https://github.com/carbon-design-system/carbon/issues/17714

2024-10-18 09:03 UTC, devadula-nandan commented on packages/ibm-products-styles/src/components/SidePanel/_side-panel.scss
> +  + .#{$block-class}__overlay
```suggestion
  + .#{$block-class}__overlay,
```

2024-10-18 09:23 UTC, devadula-nandan commented on packages/ibm-products/src/components/SidePanel/SidePanel.stories.jsx
> +    autoAlign={false}
i think we dont need to pass this false explicitly.
```suggestion
```

2024-10-18 09:43 UTC, devadula-nandan reviewed
2 comments, rest looks good to me.

2024-10-18 09:53 UTC, devadula-nandan approved these changes

2024-10-18 18:22 UTC, davidmenendez approved these changes

2024-10-18 18:29 UTC, elycheea approved these changes

2024-10-18 18:39 UTC, merged