fix(UserAvatar): release review fixes
carbon-design-system/ibm-products pull request #6293
Opened 2024-10-24 14:06 UTC by anamikaanu96

Closes #6168

Addressed released review fixes

#### What did you change? 
packages/ibm-products/src/components/UserAvatar/UserAvatar.tsx
packages/ibm-products-styles/src/components/UserAvatar/_user-avatar.scss
packages/ibm-products/src/components/UserAvatar/UserAvatar.mdx
packages/ibm-products-styles/src/components/UserAvatar/_carbon-imports.scss

#### How did you test and verify your work? storybook

2024-10-25 15:23 UTC, elycheea requested changes
A few small comments since `pointer-events` actually prevents the tooltip from working. I also found precedent in the read-only and interactive tags — I think it’s better to leave the browser default behavior in case. 🙂

But also think we can adjust the focus ring just a little bit after looking at those examples.

Lastly, I had some thoughts on showing theme this way as some of the theme stories in the `@carbon/react` Storybook do. But I also still have this stashed on a branch, so I’m happy to help open that as a followup PR to this one.

![image](https://github.com/user-attachments/assets/4ae93d3e-ad2b-4d00-98d3-31918841b93a)

2024-10-25 15:23 UTC, elycheea commented on packages/ibm-products-styles/src/components/UserAvatar/_user-avatar.scss
> +
This actually prevents the tooltip from showing up all on hover.

I think it’s better to leave this as is than to add this. You can compare this to similar components like the [read-only `Tag`](https://react.carbondesignsystem.com/?path=/story/components-tag--read-only) from Carbon. These may be more specific to the browser defaults, which is okay.

2024-10-25 15:23 UTC, elycheea commented on packages/ibm-products-styles/src/components/UserAvatar/_user-avatar.scss
I missed this before but in lines 61-64, I think we should add one more line —

```scss
outline-offset: 1px;
```
This will give us the same outline as the `OperationalTag`, which will give us better consistency and better proximity to the avatar itself.

<img width="183" alt="image" src="https://github.com/user-attachments/assets/f15e5113-184b-47e6-83d5-ae6cc58e382f">
<img width="245" alt="image" src="https://github.com/user-attachments/assets/1c0bec35-af34-4722-b4c5-60108287f70e">


```scss
.#{$block-class}__tooltip {
  &:focus-within .#{$block-class} {
    // stylelint-disable-next-line carbon/theme-token-use
    outline: 2px solid $focus;
    outline-offset: 1px;
  }
}
```

2024-10-28 19:21 UTC, elycheea approved these changes

2024-10-29 05:35 UTC, amal-k-joy approved these changes
LGTM

2024-10-29 05:45 UTC, merged