fix(API Key Modal): heading,label and downloadlink
carbon-design-system/ibm-products pull request #6298
Opened 2024-10-25 12:21 UTC by anamikaanu96

Closes #6250 and #6251

Fixed the heading text and added aria-label and role of for APIKeyDownloader
 
#### What did you change? packages/ibm-products/src/components/APIKeyModal/APIKeyDownloader.js
packages/ibm-products/src/components/APIKeyModal/APIKeyModal.tsx
packages/ibm-products/src/components/APIKeyModal/APIKeyModal.stories.jsx

#### How did you test and verify your work? voiceover

2024-10-28 13:33 UTC, amal-k-joy requested changes

2024-10-28 13:33 UTC, amal-k-joy commented on packages/ibm-products/src/components/APIKeyModal/APIKeyModal.stories.jsx
> +  modalLabel: 'An example of Generate API key',
Hi ,
Should we expose this as a prop , rather than hardcoding?

2024-10-29 08:03 UTC, amal-k-joy requested changes

2024-10-29 08:03 UTC, amal-k-joy commented on packages/ibm-products/src/components/APIKeyModal/APIKeyModal.tsx
> +                      DownloadLinkLabel={
Hi ,
Should we expose this as a optional prop , rather than hardcoding  and default to linkText ?

2024-10-30 10:08 UTC, amal-k-joy requested changes

2024-10-30 10:08 UTC, amal-k-joy commented on packages/ibm-products/src/components/APIKeyModal/APIKeyDownloader.js
> +          aria-label={DownloadLinkLabel}
Add `aria-label={DownloadLinkLabel?? linkText}` since `DownloadLinkLabel` is optional

2024-10-30 13:45 UTC, amal-k-joy submitted a review, later dismissed
Looking good

2024-11-01 09:56 UTC, devadula-nandan commented on packages/ibm-products/src/components/APIKeyModal/APIKeyDownloader.js
> +  DownloadLinkLabel,
```suggestion
  downloadLinkLabel,
```

2024-11-01 09:56 UTC, devadula-nandan commented on packages/ibm-products/src/components/APIKeyModal/APIKeyDownloader.js
> +          aria-label={DownloadLinkLabel ?? linkText}
```suggestion
          aria-label={downloadLinkLabel ?? linkText}
```

2024-11-01 09:57 UTC, devadula-nandan commented on packages/ibm-products/src/components/APIKeyModal/APIKeyDownloader.js
> +  DownloadLinkLabel: PropTypes.string,
```suggestion
  downloadLinkLabel: PropTypes.string,
```

2024-11-01 09:57 UTC, devadula-nandan commented on packages/ibm-products/src/components/APIKeyModal/APIKeyModal.tsx
> +                      DownloadLinkLabel={downloadLinkLabel}
```suggestion
                      downloadLinkLabel={downloadLinkLabel}
```

2024-11-01 09:59 UTC, devadula-nandan requested changes
prop name can be changed to camelCase

2024-11-01 14:20 UTC, anamikaanu96 commented
> prop name can be changed to camelCase

yea it should be, its added by mistake. Thanks @devadula-nandan for reviewing!

2024-11-01 14:48 UTC, devadula-nandan commented
Hi @anamikaanu96 , all good except one last thing which is confusing. 

The issue #6251 states that headings should be organized hierarchically. also, it indicates the use of H1, while I observe two H2 headings that do not follow this hierarchical structure.

should it be H2 H3 ?

2024-11-01 15:04 UTC, devadula-nandan approved these changes

2024-11-04 03:57 UTC, amal-k-joy approved these changes

2024-11-04 04:07 UTC, merged