6190  csp spreadsheet tearsheet notifications page header
carbon-design-system/ibm-products pull request #6340
Opened 2024-10-31 15:46 UTC by AlexanderMelox

Closes #6190 

This PR resolves CSP violation issues

#### What did you change?
Moved inline styles to `useIsomorphicEffect`

#### How did you test and verify your work?
Storybook

2024-11-01 17:01 UTC, AlexanderMelox commented
<img width="1133" alt="Screenshot 2024-11-01 at 1 00 55 PM" src="https://github.com/user-attachments/assets/139c08e3-3c73-4310-8aa8-645920cb22f3">
Everything is good, just having issues getting this TS type error

2024-11-01 18:33 UTC, matthewgallo commented
I think I found a way to work around this with the following added to page header:

```tsx
interface HTMLElementStyled extends HTMLElement {
  style: CSSStyleDeclaration;
}
const headerRef = (ref || localHeaderRef) as MutableRefObject<HTMLElementStyled>;
```

I just extended `HTMLElement` because when using it directly, I kept getting this read only error
![image](https://github.com/user-attachments/assets/0c55660b-8aec-42d2-822b-5b6d9af7f12f)

2024-11-01 18:43 UTC, AlexanderMelox commented
Interesting, thank you! Matt to the rescue 🛟

2024-11-06 15:34 UTC, AlexanderMelox commented
Should we remove depracted props test? or keep them and still update them?
![Screenshot 2024-11-06 at 10 34 04 AM](https://github.com/user-attachments/assets/9aa1526c-833f-405a-b1e6-3f20fd12fd4f)

2025-01-10 15:29 UTC, davidmenendez submitted a review, later dismissed

2025-01-10 15:51 UTC, matthewgallo commented on packages/ibm-products/src/components/ConditionBuilder/ConditionBuilder.types.ts
> +import { CarbonIconType } from '@carbon/icons-react';
Same thing here

2025-01-10 15:57 UTC, matthewgallo commented on packages/ibm-products/src/components/APIKeyModal/APIKeyModal.tsx
> +} from '@carbon/icons-react';
Can you share what the error was?

2025-01-10 15:59 UTC, matthewgallo requested changes
Lets see if we can import icons from `@carbon/react/icons`, also the styles in the page header seem to have been effected by these changes
<img width="1427" alt="Screenshot 2025-01-10 at 10 59 11 AM" src="https://github.com/user-attachments/assets/e3f64e3a-3e47-4ee7-a482-22d87333b2c7" />

2025-01-10 16:04 UTC, AlexanderMelox commented on packages/ibm-products/src/components/APIKeyModal/APIKeyModal.tsx
> +} from '@carbon/icons-react';
![Screenshot 2025-01-09 at 11 41 16 AM](https://github.com/user-attachments/assets/dbc098fc-3b7e-4a54-bb33-28886a6f8c5e)

2025-01-10 16:05 UTC, AlexanderMelox commented on packages/ibm-products/src/components/APIKeyModal/APIKeyModal.tsx
> +} from '@carbon/icons-react';
When importing from `@carbon/icons-react` it fixes

2025-01-10 16:12 UTC, AlexanderMelox commented on packages/ibm-products/src/components/APIKeyModal/APIKeyModal.tsx
> +} from '@carbon/icons-react';
We had a convo with Carbon core a while back and I don't know where we landed with this, FYI @tay1orjones

2025-01-10 16:56 UTC, AlexanderMelox commented on packages/ibm-products/src/components/ConditionBuilder/ConditionBuilder.types.ts
> +import { CarbonIconType } from '@carbon/icons-react';
![Screenshot 2025-01-10 at 11 55 58 AM](https://github.com/user-attachments/assets/6d5380fb-2381-49b0-9696-d81996fb6af4)

I changed it for this reason

2025-01-10 16:57 UTC, AlexanderMelox commented on packages/ibm-products/src/components/ConditionBuilder/ConditionBuilder.types.ts
> +import { CarbonIconType } from '@carbon/icons-react';
So i had to change the import to fix this error

2025-01-10 17:58 UTC, AlexanderMelox commented
@matthewgallo fixed page header styles !

2025-01-10 18:26 UTC, matthewgallo commented
Sorry, one more style change! I just noticed that the entrance animation for the notification panel is also missing with the current changes.

2025-01-13 21:41 UTC, matthewgallo requested changes
Just spotted one more style change in the [stacked tearsheets](https://deploy-preview-6340--carbon-for-ibm-products.netlify.app/?path=/story/ibm-products-components-tearsheet--stacked-mixed-sizes&globals=viewport:basic) that looks unintended.

2025-01-13 22:04 UTC, AlexanderMelox commented
> Just spotted one more style change in the [stacked tearsheets](https://deploy-preview-6340--carbon-for-ibm-products.netlify.app/?path=/story/ibm-products-components-tearsheet--stacked-mixed-sizes&globals=viewport:basic) that looks unintended.

I see its the same issue when using CSS properties, nice catch

2025-01-13 22:12 UTC, AlexanderMelox commented
@matthewgallo fixed, i assume it was the size of the tearsheet?

Before: 
![Screenshot 2025-01-13 at 5 12 03 PM](https://github.com/user-attachments/assets/b1c7c7d2-3b8a-4046-a234-6eda2e9e7e40)

After:
![Screenshot 2025-01-13 at 5 12 33 PM](https://github.com/user-attachments/assets/418f538b-0eba-4785-acb9-48df8db7e0ef)

2025-01-14 14:17 UTC, AlexanderMelox commented on packages/ibm-products/src/components/NotificationsPanel/NotificationsPanel.tsx
> +          console.log({ open, notificationPanelRef });
```suggestion
```

2025-01-14 14:28 UTC, davidmenendez approved these changes

2025-01-14 15:09 UTC, merged