deprecate experimental security components with low usage
carbon-design-system/ibm-products pull request #6396
Opened 2024-11-08 10:56 UTC by makafsal

Closes #6318 

#### What did you change?
Annotated deprecation notice in the following components:
1. Decorator dual button
2. Decorator link
3. Decorator single button
4. Description list
5. Nav
6. Status indicator
7. Status indicator step

#### How did you test and verify your work?
`yarn test`
Storybook

2024-11-12 14:28 UTC, matthewgallo reviewed
This is looking good. There are [some suggestions](https://github.com/carbon-design-system/ibm-products/pull/6401#pullrequestreview-2428012332) I made in https://github.com/carbon-design-system/ibm-products/pull/6401 that also apply here as well.

I also think you could cleanup the stories files by using the `decorators` property from the default story export, so you can wrap each story with the `Annotation` component.

2024-11-14 14:08 UTC, AlexanderMelox approved these changes

2024-11-15 16:45 UTC, davidmenendez requested changes
LGTM just one minor thing!

2024-11-15 16:45 UTC, davidmenendez commented on packages/ibm-products/src/components/DecoratorDualButton/DecoratorDualButton.mdx
> +## Deprecated
can you update these headers to `Deprecation notice` in order to align with the new `deprecationNotice` prop in `StoryDocsPage`?

2024-11-20 19:27 UTC, davidmenendez approved these changes

2024-11-20 20:58 UTC, matthewgallo approved these changes

2024-11-20 21:09 UTC, merged