chore(FilterPanel): deprecare filter panel and its sub components
carbon-design-system/ibm-products pull request #6431
Opened 2024-11-14 09:30 UTC by amal-k-joy

Closes #6320 

#### What did you change?
Annotated deprecation notice in Filter panel and its sub stories

#### How did you test and verify your work?
storybook
yarn test

2024-11-15 16:31 UTC, davidmenendez requested changes
looks good, just one minor thing!

2024-11-15 16:31 UTC, davidmenendez commented on packages/ibm-products/src/components/FilterPanel/FilterPanel.mdx
> +## Deprecated
very minor, but can you change these headers to `Deprecation notice` to align with the `deprecationNotice` prop in `StoryDocsPage.js`?

2024-11-15 16:40 UTC, devadula-nandan commented
these are the initial snapshots, so 168 visual changes is expected, until we merge any pr with approved visual changes, they keep appearing.

2024-11-19 06:42 UTC, sangeethababu9223 approved these changes

2024-11-20 19:12 UTC, davidmenendez approved these changes

2024-11-20 19:22 UTC, merged