fix(EmptyState): empty states throws hydration errors in next js due to dynamic id
carbon-design-system/ibm-products pull request #6508
Opened 2024-11-26 08:21 UTC by amal-k-joy

Closes #6315 

Hydration error will happen in next js when any dynamic ids is used in the dom. Here we were using unique dynamic ids to the svg elements generated using uuid4() which was added as part of another [issue fix](https://github.com/carbon-design-system/ibm-products/pull/1290). 
Currently , i have exposed a prop, `svgId` , where user can optionally pass any static id, which will solve dynamic id issues in empty states.

#### How did you test and verify your work?
next js application

2024-11-26 19:23 UTC, davidmenendez requested changes
this actually seems like a good use case for [useId](https://react.dev/reference/react/useId). i think we should consider using this instead of `uuidv4`. this should alleviate the problem without need for introducing a new prop. the docs do mention a pitfall with SSR though:

> With [server rendering](https://react.dev/reference/react-dom/server), useId requires an identical component tree on the server and the client. If the trees you render on the server and the client don’t match exactly, the generated IDs won’t match.

i'm not very familiar with next and SSR's though, so i'm not sure if this will solve this specific issue. if not then a static prop might be the way to go. but i'm confident that `useId` will be fine here.

2024-11-27 06:07 UTC, amal-k-joy commented
> this actually seems like a good use case for [useId](https://react.dev/reference/react/useId). i think we should consider using this instead of `uuidv4`. this should alleviate the problem without need for introducing a new prop. the docs do mention a pitfall with SSR though:
> 
> > With [server rendering](https://react.dev/reference/react-dom/server), useId requires an identical component tree on the server and the client. If the trees you render on the server and the client don’t match exactly, the generated IDs won’t match.
> 
> i'm not very familiar with next and SSR's though, so i'm not sure if this will solve this specific issue. if not then a static prop might be the way to go. but i'm confident that `useId` will be fine here.

Hey @davidmenendez ,
Thanks for the good catch. `useId` can be used here, since its consistent across client and server side rendering.

> The useId hook in React 18 and later is a powerful tool for generating unique IDs that are consistent across client-side and server-side rendering.

2024-11-27 14:06 UTC, davidmenendez approved these changes

2024-11-28 05:14 UTC, makafsal approved these changes

2024-11-28 05:24 UTC, merged