feat(sidepanel): implement decorator prop
carbon-design-system/ibm-products pull request #6511
Opened 2024-11-27 05:50 UTC by makafsal

Closes #6454 

#### What did you change?
implemented a new prop `decorator` and deprecated `aiLabel`

#### How did you test and verify your work?
`yarn test`
storybook

2024-12-05 07:16 UTC, anamikaanu96 requested changes
Hi @makafsal, the AI label doesn't seem to be working in some of the stories, such as SlideIn and Panel with the second step. There are some inconsistencies. Could you please check?

2024-12-06 04:58 UTC, makafsal commented
> Hi @makafsal, the AI label doesn't seem to be working in some of the stories, such as SlideIn and Panel with the second step. There are some inconsistencies. Could you please check?

Done.

2024-12-09 06:40 UTC, anamikaanu96 approved these changes
LGTM

2024-12-10 19:16 UTC, AlexanderMelox approved these changes

2024-12-10 19:35 UTC, merged