chore: update stylelint from v15 to v16
carbon-design-system/ibm-products pull request #6515
Opened 2024-11-27 20:27 UTC by davidmenendez

Closes #6424 

major dependency upgrades for `stylelint` from `v15` to `v16` and `stylelint-plugin-carbon-tokens` from '2.8.0` to `3.2.1`

2024-11-27 20:48 UTC, elycheea requested changes
Much better! Some smaller changes and observations —

1. Are the AI tokens not captured in `stylelint-plugin-carbon-tokens`? If so, we should check in with Lee.
2. Caught a few places that look like redundant disables. If we can remove them, we should.
3. ^ some of those were using a namespace. I would expect `stylelint-plugin-carbon-tokens` to work with them, in which case they are redundant again. If not, we should follow up with Lee.

2024-11-27 20:48 UTC, elycheea commented on examples/carbon-for-ibm-products/Cascade/src/Example/_example.scss
> +  // stylelint-disable-next-line carbon/theme-use
```suggestion
```

Wouldn’t this one count as token use? 🤔

2024-11-27 20:48 UTC, elycheea commented on packages/ibm-products-styles/src/components/CreateTearsheet/_create-tearsheet.scss
> +    // stylelint-disable-next-line carbon/layout-use
```suggestion
```

Since this was updated to a token, we can probably remove this line.

2024-11-27 20:48 UTC, elycheea commented on packages/ibm-products-styles/src/components/Datagrid/styles/_datagrid.scss
> +  /* stylelint-disable-next-line carbon/theme-use */
Are AI tokens not captured in the `stylelint-plugin-carbon-tokens` package or is this just leftover from maybe an earlier version? 👀

2024-11-27 20:48 UTC, elycheea commented on packages/ibm-products-styles/src/components/Datagrid/styles/addons/_RowSizeDropdown.scss
> +  /* stylelint-disable-next-line carbon/layout-use */
```suggestion
```

2024-11-27 20:48 UTC, elycheea commented on packages/ibm-products-styles/src/components/EditTearsheet/_edit-tearsheet.scss
> +    // stylelint-disable-next-line carbon/layout-use
```suggestion
```

2024-11-27 20:48 UTC, elycheea commented on packages/ibm-products-styles/src/components/OptionsTile/_options-tile.scss
> +  // stylelint-disable-next-line carbon/layout-use
```suggestion
```

2024-11-27 20:48 UTC, elycheea commented on packages/ibm-products-styles/src/components/OptionsTile/_options-tile.scss
> +  // stylelint-disable-next-line carbon/layout-use
```suggestion
```

2024-11-27 20:48 UTC, elycheea commented on packages/ibm-products-styles/src/components/PageHeader/_page-header.scss
> +    // stylelint-disable-next-line carbon/layout-use
```suggestion
```

2024-11-27 20:48 UTC, elycheea commented on packages/ibm-products-styles/src/components/SidePanel/_side-panel.scss
> +  /* stylelint-disable-next-line carbon/theme-use */
Another AI theme token. 🤔

2024-11-27 20:48 UTC, elycheea commented on packages/ibm-products/src/components/Coachmark/_storybook-styles.scss
> +  /* stylelint-disable-next-line carbon/layout-use */
```suggestion
```

2024-11-27 20:48 UTC, elycheea commented on packages/ibm-products/src/components/CoachmarkBeacon/_storybook-styles.scss
> +  /* stylelint-disable-next-line carbon/layout-use */
```suggestion
```

2024-11-27 20:48 UTC, elycheea commented on packages/ibm-products/src/components/CoachmarkButton/_storybook-styles.scss
> +  /* stylelint-disable-next-line carbon/layout-use */
```suggestion
```

2024-11-27 20:48 UTC, elycheea commented on packages/ibm-products/src/components/CoachmarkOverlayElement/_storybook-styles.scss
> +  /* stylelint-disable-next-line carbon/layout-use */
```suggestion
```

2024-11-27 20:48 UTC, elycheea commented on packages/ibm-products/src/components/CoachmarkOverlayElements/_storybook-styles.scss
> +  /* stylelint-disable-next-line carbon/layout-use */
```suggestion
```

2024-11-27 20:48 UTC, elycheea commented on packages/ibm-products/src/components/CreateModal/_storybook-styles.scss
> +  /* stylelint-disable-next-line carbon/layout-use */
```suggestion
```

2024-11-27 20:48 UTC, elycheea commented on packages/ibm-products/src/components/TruncatedList/_storybook-styles.scss
> +  /* stylelint-disable-next-line carbon/layout-use */
```suggestion
```

2024-11-27 20:48 UTC, elycheea commented on packages/ibm-products/src/components/UserAvatar/_storybook-styles.scss
> +  /* stylelint-disable-next-line carbon/layout-use */
```suggestion
```

Assuming these _should_ work when namespaced, but if not, we may need to keep this in place for now.

2024-11-27 20:48 UTC, elycheea commented on packages/ibm-products/src/components/UserAvatar/_storybook-styles.scss
> +  /* stylelint-disable-next-line carbon/layout-use */
```suggestion
```

Again, assuming the namespaced tokens should still work with the plugin.

2024-12-02 20:09 UTC, davidmenendez commented
@elycheea @matthewgallo looks like everything is building properly now and should be ready for review 👍

2024-12-02 21:19 UTC, elycheea submitted a review, later dismissed

2024-12-02 21:25 UTC, matthewgallo approved these changes
Nice! I do think we could use a spacing token for the theme dropdown in the examples (`examples/carbon-for-ibm-products/*/src/ThemeSelector/_theme-dropdown.scss`), I noticed _a lot_ of repeated disabling in those files. But lets take a look after we get these changes in.

2024-12-02 21:28 UTC, davidmenendez commented
totally agree. there's **a lot** of cleanup that we can do around the scss files, specifically around taking a look at anything that's not using tokens and removing redundant code, which seems to be prevalent in storybook specific styles.

2024-12-03 15:21 UTC, davidmenendez commented
@elycheea & @matthewgallo when you have a sec to re-review 👀 🙇

2024-12-03 15:25 UTC, matthewgallo approved these changes

2024-12-03 21:44 UTC, elycheea approved these changes

2024-12-03 21:54 UTC, merged