test(ProductiveCard): add avt test coverage
carbon-design-system/ibm-products pull request #6518
Opened 2024-11-29 14:38 UTC by devadula-nandan

Closes #6472

adds accessibility tests for productive card

Since we are in v12 OverflowMenu. i noticed that passing aria-label prop to v12 OverflowMenu spreads it to the overflow menu container which is a div and is reported as violation
v12 OverflowMenu uses single `Label` prop to set tooltip text on menu button and aria-label for list container (ul)
which means we might need to deprecate either `iconDescription` or `overflowAriaLabel` as `Label` prop handles both with v12 OverflowMenu.

useful references
https://github.com/carbon-design-system/ibm-products/pull/5803
https://github.com/carbon-design-system/ibm-products/pull/6395

i have passed label as below, and awaiting for any review suggestions
```
label={iconDescription || overflowAriaLabel}
```

#### What did you change?
e2e/components/ProductiveCard/ProductiveCard-test.avt.e2e.js
packages/ibm-products/src/components/Card/Card.tsx

#### How did you test and verify your work?
yarn avt

2024-12-04 22:10 UTC, elycheea reviewed
Looks good overall, but I think there are a few places where we could also use role/text locators rather than by query selectors. :)

2024-12-04 22:10 UTC, elycheea commented on e2e/components/ProductiveCard/ProductiveCard-test.avt.e2e.js
> +    expect(await disabledButton.getAttribute('disabled')).not.toBeNull();
I think we typically try to query by role or text over a specific query selector.

In this case, we could probably do 

```js
const disabledButton = page.getByRole('button', { name: 'Read more' });
```

Or some similar variation of that.

2024-12-04 22:10 UTC, elycheea commented on e2e/components/ProductiveCard/ProductiveCard-test.avt.e2e.js
> +    const menu = page.locator('ul[role="menu"]');
We can probably use the roles here as well. :)

https://playwright.dev/docs/locators#locate-by-role

2024-12-05 08:17 UTC, devadula-nandan commented
@elycheea fixed it

2024-12-05 21:18 UTC, elycheea approved these changes
Also agree it might be good to deprecate `iconDescription` or `overflowAriaLabel` if they are now redundant. If `iconDescription` overrides `overflowAriaLabel`, that may be preferable unless the latter is more widely used. 🤔

2024-12-06 08:21 UTC, devadula-nandan commented
> Also agree it might be good to deprecate `iconDescription` or `overflowAriaLabel` if they are now redundant. If `iconDescription` overrides `overflowAriaLabel`, that may be preferable unless the latter is more widely used. 🤔

im pretty sure we can deprecate `iconDescription` as it has been introduced recently compared to `overflowAriaLabel`.
also changed the override order to prioritise `overflowAriaLabel`. and updated the pr accordingly.

although a more generic name `label` could be more convenient (just like we have in core. a common prop to pass to button tooltip and aria-label for v12 OverflowMenu) when compared to having `overflowAriaLabel` that also sets tooltip text.

any additional thoughts or suggestions?

2024-12-06 18:11 UTC, elycheea approved these changes

2024-12-09 09:15 UTC, anamikaanu96 requested changes
Hi @devadula-nandan can you add test for hover state.

2024-12-09 15:06 UTC, elycheea approved these changes

2024-12-11 10:55 UTC, devadula-nandan commented
@anamikaanu96 done

2024-12-11 11:16 UTC, anamikaanu96 approved these changes

2024-12-11 11:26 UTC, merged