fix(Emptystate): accessibility violation
carbon-design-system/ibm-products pull request #6605
Opened 2024-12-18 10:36 UTC by anamikaanu96

Closes #6352 

Solutions for empty state accessibility violations
solution for issue 1 : Heading is now composable , introduced a new prop called `headingAs` for setting the value of `as`.
solution issue 2 : since the images are decorative, they have been hidden from assistive technology.

I had a discussion with Amal today regarding the conversation in the engineering huddle. We concluded that more appropriate solution will be using `as` prop rather than using <Heading> without deprecating size prop. 

#### What did you change? All EmptyState files

#### How did you test and verify your work? storybook and Jaws

2024-12-19 06:45 UTC, amal-k-joy requested changes

2024-12-19 06:45 UTC, amal-k-joy commented on packages/ibm-products/src/components/EmptyStates/EmptyState.tsx
> +      headingAs,
We can give a default value for `headingAs ` as 'h3', since currently we have this as h3

2024-12-20 10:13 UTC, amal-k-joy approved these changes
LGTM

2024-12-30 16:14 UTC, davidmenendez approved these changes

2024-12-30 16:24 UTC, merged