fix: add null check for callback
carbon-design-system/ibm-products pull request #6633
Opened 2024-12-31 08:59 UTC by amal-k-joy

Closes #6547 

Added a null check for `toggleRowSelected` callback

#### How did you test and verify your work?
local

2025-01-07 14:23 UTC, AlexanderMelox requested changes
Looks good just one small suggestion

2025-01-07 14:23 UTC, AlexanderMelox commented on packages/ibm-products/src/components/Datagrid/useOnRowClick.ts
> +                  toggleRow.toggleRowSelected(false)
```suggestion
              instance.selectedFlatRows.map(
                (toggleRow) =>
                  toggleRow.toggleRowSelected?.(false)
```

2025-01-07 14:23 UTC, AlexanderMelox commented on packages/ibm-products/src/components/Datagrid/useOnRowClick.ts
> +                  toggleRow.toggleRowSelected(false)
We can make it more concise with an optional chaining operator

2025-01-13 14:27 UTC, anamikaanu96 approved these changes

2025-01-13 14:56 UTC, AlexanderMelox approved these changes

2025-01-13 15:05 UTC, merged